### ISSUE TITLE
SHA-256 hash mismatch

### ISSUE THREAD

**Issue by martinkrung** [hicommonwealth/edgeware-lockdrop#15]
What I do:

`wget https://raw.githubusercontent.com/hicommonwealth/edgeware-lockdrop/master/contracts/Lockdrop.sol
`

`sha256sum Lockdrop.sol`
`155e969ad7b2266bdf1a6f8be7a7b2606bca2f7fd9003d9c0191bcc8e033ffb9  Lockdrop.sol`

SHA-256 hash should be:
`b3089fc52a09660f632e308089af690aee2475e1ecfaec53301e886214f71251 ./contracts/Lockdrop.sol`

Source: **Appendix Section**
https://arena-attachments.s3.amazonaws.com/4282493/a155dc84aa1dfba4cfd3dc6be1e1ebdc.pdf?1557965252

Also in this document:

"2019-04-08 - Reviewed report based on commit 51478f1"

But there is no such commit in this branch, only in another branch?

And if you changed Lockdrop.sol since the audit, what did you change?

Thanks for clarif!

**Comment by drewstone** [comment]
Hey @martinkrung, we're definitely on this to try and get Quanstamp to update the hash. The only thing that was changed was changing to the name `edgewareAddr` from `edgewareKey` in the functions.

**Comment by martinkrung** [comment]
had seen this change from edgewareKey to edgewareAddr somewhere. this makes sens because thats what it is, a address
